import { Suspense, createElement } from 'react'
//import HeaderTop from '@/components/HeaderTop/page';
import dynamic from 'next/dynamic'
import IOComponent from '../components/IOComponent/page'
import './globals.css'
import styles from "./page.module.css";
import Image from "next/image";
import bigImage from "./big.svg";
import { Passion_One } from 'next/font/google';


const passion = Passion_One({
  subsets: ['latin'],
  display: 'swap',
  style: "normal",
  weight: "400"
});
/*const IOComponent = dynamic(() => import('../components/IOComponent/page'), {
  loading: () => <span>Loading...</span>, ssr: false
})*/
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
export default async function Layout(props) {
  //   <body style={{position: 'relative'}}>
  //const ssr_worker = new Worker('./worker.js')//, { workerData: { arr: arrParams } })
  //ssr_worker.on('message', (message) => console.log('server action', message))
  return (
    <html lang="ru">
      <body>
        <div key='next' id='__next'>
          <header className={styles.header} id='header'>
            <h1 className={passion.className}>ARMAGEDDON 2023</h1>
            <div className={styles.command}>
              <span>
                ООО “Команда им. Б. Уиллиса”.
              </span>
              <span>
                Взрываем астероиды с 1998 года.
              </span>
            </div>
          </header>
          <div className='grid'>
            <div className={styles.hidden}>
              <Image src={bigImage} alt="Earth" priority />
            </div>
            <Suspense fallback={<span className={'loader'}></span>}>
              {props.children}
            </Suspense>
          </div>
          <Suspense><IOComponent /></Suspense>
        </div>
      </body>
    </html >
  )
}
