import styles from "./page.module.css";
import React, { createElement, Suspense } from "react";

import Form from "next/form";
import Link from "next/link";
//import { marked } from "../../../actions/marked"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function BasketLayout({
  children,
}/*: {
    children: React.ReactNode
}*/) {
  return <footer className={styles.footer}>
    <div className={styles.columnFooter}>
      <span className={styles.h3}>Корзина</span>
      <div>
        <output className={styles.padding_count}>{children}</output>
        <span className={styles.aster}>астероида</span>
      </div>
    </div>
    <nav className={styles.rrrr}>
      <Link href="/categories?viewtype=marked" scroll={false}
        className={styles.button}>
        <span className={styles.padding}>Отправить</span>
      </Link>
    </nav>
  </footer>
}
